[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Pedro Diogo"]

[dependencies]
scan_fmt = "0.2.5"
rayon = "1.5.0"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "benchmarks"
harness = false